// Write Create a structure called train containing the following members:
// - trainno: Representing the train number
// - trainname: Representing the train name
// - src : Representing the starting station of train
// - dst: Representing the destination station of the train
// - price: Representing the price of one ticket from source to destination.
// - noofcoaches: Representing the number of coaches which will be there in the train.
// Write
// - A function read_train to read the details from the input and store it in a structure
// variable.
// - A function display_train to display all details of the train as shown in sample
// output.
// - A function calc_income to calculate the income generated by railways by
// operating this train. (Assume each coach can carry 72 passengers).

#include <stdio.h>
#include <string.h>
struct train
{
    int trainno, price, noofcoaches;
    char trainname[20], src[20], dst[20];
};
void read_train(struct train *t);
void display_train(struct train *t);
void calc_income(struct train *t);
int main()
{
    struct train t;
    read_train(&t);
    display_train(&t);
    calc_income(&t);
    return 0;
}
void read_train(struct train *t)

{
    scanf("%d\n", &t->trainno);
    scanf("%s", t->trainname);
    scanf("%s", t->src);
    scanf("%s", t->dst);
    scanf("%d", &t->price);
    scanf("%d", &t->noofcoaches);
}
void display_train(struct train *t)
{
    printf("Train Number: %d\n", t->trainno);
    printf("Train Name: %s\n", t->trainname);
    printf("Starting At: %s\n", t->src);
    printf("Ending At: %s\n", t->dst);
    printf("Price of Each Ticket: %d\n", t->price);
    printf("Number of Coaches Attached: %d\n", t->noofcoaches);
}
void calc_income(struct train *t)
{
    printf("Income Generated: %d", (t->noofcoaches * 72) * t->price);
}